/* Generated by wayland-scanner 1.24.0 */

#ifndef FULLSCREEN_SHELL_UNSTABLE_V1_SERVER_PROTOCOL_H
#define FULLSCREEN_SHELL_UNSTABLE_V1_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_fullscreen_shell_unstable_v1 The fullscreen_shell_unstable_v1 protocol
 * @section page_ifaces_fullscreen_shell_unstable_v1 Interfaces
 * - @subpage page_iface_zwp_fullscreen_shell_v1 - displays a single surface per output
 * - @subpage page_iface_zwp_fullscreen_shell_mode_feedback_v1 - 
 * @section page_copyright_fullscreen_shell_unstable_v1 Copyright
 * <pre>
 *
 * Copyright © 2016 Yong Bakos
 * Copyright © 2015 Jason Ekstrand
 * Copyright © 2015 Jonas Ådahl
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * </pre>
 */
struct wl_output;
struct wl_surface;
struct zwp_fullscreen_shell_mode_feedback_v1;
struct zwp_fullscreen_shell_v1;

#ifndef ZWP_FULLSCREEN_SHELL_V1_INTERFACE
#define ZWP_FULLSCREEN_SHELL_V1_INTERFACE
/**
 * @page page_iface_zwp_fullscreen_shell_v1 zwp_fullscreen_shell_v1
 * @section page_iface_zwp_fullscreen_shell_v1_desc Description
 *
 * Displays a single surface per output.
 *
 * This interface provides a mechanism for a single client to display
 * simple full-screen surfaces.  While there technically may be multiple
 * clients that bind to this interface, only one client should bind to
 * it at a time.
 *
 * To form the surfaces to be displayed, the client creates one or more
 * wl_surfaces.  It then requests one of those surfaces to be displayed
 * on a given output.  The client may also request a mode switch to
 * a particular mode.
 *
 * When a surface is presented on an output, that output is considered
 * to be "owned" by the client and the client should expect to receive
 * all input from that output.  If the client wants to present the same
 * surface on multiple outputs, it should request the surface be presented
 * on each output individually.
 *
 * If the client releases the interface, all surfaces presented by the
 * client are removed from the outputs.
 * @section page_iface_zwp_fullscreen_shell_v1_api API
 * See @ref iface_zwp_fullscreen_shell_v1.
 */
/**
 * @defgroup iface_zwp_fullscreen_shell_v1 The zwp_fullscreen_shell_v1 interface
 *
 * Displays a single surface per output.
 *
 * This interface provides a mechanism for a single client to display
 * simple full-screen surfaces.  While there technically may be multiple
 * clients that bind to this interface, only one client should bind to
 * it at a time.
 *
 * To form the surfaces to be displayed, the client creates one or more
 * wl_surfaces.  It then requests one of those surfaces to be displayed
 * on a given output.  The client may also request a mode switch to
 * a particular mode.
 *
 * When a surface is presented on an output, that output is considered
 * to be "owned" by the client and the client should expect to receive
 * all input from that output.  If the client wants to present the same
 * surface on multiple outputs, it should request the surface be presented
 * on each output individually.
 *
 * If the client releases the interface, all surfaces presented by the
 * client are removed from the outputs.
 */
extern const struct wl_interface zwp_fullscreen_shell_v1_interface;
#endif
#ifndef ZWP_FULLSCREEN_SHELL_MODE_FEEDBACK_V1_INTERFACE
#define ZWP_FULLSCREEN_SHELL_MODE_FEEDBACK_V1_INTERFACE
/**
 * @page page_iface_zwp_fullscreen_shell_mode_feedback_v1 zwp_fullscreen_shell_mode_feedback_v1
 * @section page_iface_zwp_fullscreen_shell_mode_feedback_v1_api API
 * See @ref iface_zwp_fullscreen_shell_mode_feedback_v1.
 */
/**
 * @defgroup iface_zwp_fullscreen_shell_mode_feedback_v1 The zwp_fullscreen_shell_mode_feedback_v1 interface
 */
extern const struct wl_interface zwp_fullscreen_shell_mode_feedback_v1_interface;
#endif

#ifndef ZWP_FULLSCREEN_SHELL_V1_CAPABILITY_ENUM
#define ZWP_FULLSCREEN_SHELL_V1_CAPABILITY_ENUM
/**
 * @ingroup iface_zwp_fullscreen_shell_v1
 * capabilities advertised by the compositor
 *
 * Various capabilities that can be advertised by the compositor.  They
 * are advertised one-at-a-time when the interface is first bound.
 */
enum zwp_fullscreen_shell_v1_capability {
	/**
	 * compositor is capable of some arbitrary modes
	 */
	ZWP_FULLSCREEN_SHELL_V1_CAPABILITY_ARBITRARY_MODES = 1,
	/**
	 * compositor has a separate cursor plane
	 */
	ZWP_FULLSCREEN_SHELL_V1_CAPABILITY_CURSOR_PLANE = 2,
};
#endif /* ZWP_FULLSCREEN_SHELL_V1_CAPABILITY_ENUM */

#ifndef ZWP_FULLSCREEN_SHELL_V1_CAPABILITY_ENUM_IS_VALID
#define ZWP_FULLSCREEN_SHELL_V1_CAPABILITY_ENUM_IS_VALID
/**
 * @ingroup iface_zwp_fullscreen_shell_v1
 * Validate a zwp_fullscreen_shell_v1 capability value.
 *
 * @return true on success, false on error.
 * @ref zwp_fullscreen_shell_v1_capability
 */
static inline bool
zwp_fullscreen_shell_v1_capability_is_valid(uint32_t value, uint32_t version) {
	switch (value) {
	case ZWP_FULLSCREEN_SHELL_V1_CAPABILITY_ARBITRARY_MODES:
		return version >= 1;
	case ZWP_FULLSCREEN_SHELL_V1_CAPABILITY_CURSOR_PLANE:
		return version >= 1;
	default:
		return false;
	}
}
#endif /* ZWP_FULLSCREEN_SHELL_V1_CAPABILITY_ENUM_IS_VALID */

#ifndef ZWP_FULLSCREEN_SHELL_V1_PRESENT_METHOD_ENUM
#define ZWP_FULLSCREEN_SHELL_V1_PRESENT_METHOD_ENUM
/**
 * @ingroup iface_zwp_fullscreen_shell_v1
 * different methods to set the surface fullscreen
 *
 * Hints to indicate to the compositor how to deal with a conflict
 * between the dimensions of the surface and the dimensions of the
 * output. The compositor is free to ignore these hints.
 */
enum zwp_fullscreen_shell_v1_present_method {
	/**
	 * no preference, apply default policy
	 */
	ZWP_FULLSCREEN_SHELL_V1_PRESENT_METHOD_DEFAULT = 0,
	/**
	 * center the surface on the output
	 */
	ZWP_FULLSCREEN_SHELL_V1_PRESENT_METHOD_CENTER = 1,
	/**
	 * scale the surface, maintaining aspect ratio, to the largest size that will fit on the output
	 */
	ZWP_FULLSCREEN_SHELL_V1_PRESENT_METHOD_ZOOM = 2,
	/**
	 * scale the surface, maintaining aspect ratio, to fully cover the output, cropping if needed
	 */
	ZWP_FULLSCREEN_SHELL_V1_PRESENT_METHOD_ZOOM_CROP = 3,
	/**
	 * scale the surface to the size of the output, ignoring aspect ratio
	 */
	ZWP_FULLSCREEN_SHELL_V1_PRESENT_METHOD_STRETCH = 4,
};
#endif /* ZWP_FULLSCREEN_SHELL_V1_PRESENT_METHOD_ENUM */

#ifndef ZWP_FULLSCREEN_SHELL_V1_PRESENT_METHOD_ENUM_IS_VALID
#define ZWP_FULLSCREEN_SHELL_V1_PRESENT_METHOD_ENUM_IS_VALID
/**
 * @ingroup iface_zwp_fullscreen_shell_v1
 * Validate a zwp_fullscreen_shell_v1 present_method value.
 *
 * @return true on success, false on error.
 * @ref zwp_fullscreen_shell_v1_present_method
 */
static inline bool
zwp_fullscreen_shell_v1_present_method_is_valid(uint32_t value, uint32_t version) {
	switch (value) {
	case ZWP_FULLSCREEN_SHELL_V1_PRESENT_METHOD_DEFAULT:
		return version >= 1;
	case ZWP_FULLSCREEN_SHELL_V1_PRESENT_METHOD_CENTER:
		return version >= 1;
	case ZWP_FULLSCREEN_SHELL_V1_PRESENT_METHOD_ZOOM:
		return version >= 1;
	case ZWP_FULLSCREEN_SHELL_V1_PRESENT_METHOD_ZOOM_CROP:
		return version >= 1;
	case ZWP_FULLSCREEN_SHELL_V1_PRESENT_METHOD_STRETCH:
		return version >= 1;
	default:
		return false;
	}
}
#endif /* ZWP_FULLSCREEN_SHELL_V1_PRESENT_METHOD_ENUM_IS_VALID */

#ifndef ZWP_FULLSCREEN_SHELL_V1_ERROR_ENUM
#define ZWP_FULLSCREEN_SHELL_V1_ERROR_ENUM
enum zwp_fullscreen_shell_v1_error {
	/**
	 * present_method is not known
	 */
	ZWP_FULLSCREEN_SHELL_V1_ERROR_INVALID_METHOD = 0,
};
#endif /* ZWP_FULLSCREEN_SHELL_V1_ERROR_ENUM */

#ifndef ZWP_FULLSCREEN_SHELL_V1_ERROR_ENUM_IS_VALID
#define ZWP_FULLSCREEN_SHELL_V1_ERROR_ENUM_IS_VALID
/**
 * @ingroup iface_zwp_fullscreen_shell_v1
 * Validate a zwp_fullscreen_shell_v1 error value.
 *
 * @return true on success, false on error.
 * @ref zwp_fullscreen_shell_v1_error
 */
static inline bool
zwp_fullscreen_shell_v1_error_is_valid(uint32_t value, uint32_t version) {
	switch (value) {
	case ZWP_FULLSCREEN_SHELL_V1_ERROR_INVALID_METHOD:
		return version >= 1;
	default:
		return false;
	}
}
#endif /* ZWP_FULLSCREEN_SHELL_V1_ERROR_ENUM_IS_VALID */

/**
 * @ingroup iface_zwp_fullscreen_shell_v1
 * @struct zwp_fullscreen_shell_v1_interface
 */
struct zwp_fullscreen_shell_v1_interface {
	/**
	 * release the zwp_fullscreen_shell_v1 interface
	 *
	 * Release the binding from the zwp_fullscreen_shell_v1
	 * interface. Any surfaces presented by this client will be hidden
	 * and the outputs they were presented on will be released.
	 */
	void (*release)(struct wl_client *client,
			struct wl_resource *resource);
	/**
	 * present surface for display
	 *
	 * Present a surface on the given output.
	 *
	 * If the output is null, the compositor will present the surface
	 * on whatever output (or outputs) it deems appropriate. In
	 * particular, this may replace any previous surface presented on
	 * that output.
	 *
	 * The method parameter is a hint to the compositor for how the
	 * surface should be presented. The compositor is free to ignore
	 * this hint.
	 */
	void (*present_surface)(struct wl_client *client,
				struct wl_resource *resource,
				struct wl_resource *surface,
				uint32_t method,
				struct wl_resource *output);
	/**
	 * present surface for display at a particular mode
	 *
	 * Presents a surface on the given output for a particular mode.
	 *
	 * If the current size of the output differs from that of the
	 * surface, the compositor will attempt to change the size of the
	 * output to match the surface. The result of the mode-switch
	 * operation will be returned via the provided
	 * zwp_fullscreen_shell_mode_feedback_v1 object.
	 *
	 * If the presented surface is null, then the output's mode will be
	 * changed to the one requested and the output will show a black
	 * screen.
	 *
	 * If the framerate parameter is 0, the compositor will choose the
	 * framerate. If the framerate parameter is not 0, the compositor
	 * will attempt to match the framerate.
	 */
	void (*present_surface_for_mode)(struct wl_client *client,
					 struct wl_resource *resource,
					 struct wl_resource *surface,
					 struct wl_resource *output,
					 int32_t framerate,
					 uint32_t feedback);
};

#define ZWP_FULLSCREEN_SHELL_V1_CAPABILITY 0

/**
 * @ingroup iface_zwp_fullscreen_shell_v1
 */
#define ZWP_FULLSCREEN_SHELL_V1_CAPABILITY_SINCE_VERSION 1

/**
 * @ingroup iface_zwp_fullscreen_shell_v1
 */
#define ZWP_FULLSCREEN_SHELL_V1_RELEASE_SINCE_VERSION 1
/**
 * @ingroup iface_zwp_fullscreen_shell_v1
 */
#define ZWP_FULLSCREEN_SHELL_V1_PRESENT_SURFACE_SINCE_VERSION 1
/**
 * @ingroup iface_zwp_fullscreen_shell_v1
 */
#define ZWP_FULLSCREEN_SHELL_V1_PRESENT_SURFACE_FOR_MODE_SINCE_VERSION 1

/**
 * @ingroup iface_zwp_fullscreen_shell_v1
 * Sends an capability event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
zwp_fullscreen_shell_v1_send_capability(struct wl_resource *resource_, uint32_t capability)
{
	wl_resource_post_event(resource_, ZWP_FULLSCREEN_SHELL_V1_CAPABILITY, capability);
}

#define ZWP_FULLSCREEN_SHELL_MODE_FEEDBACK_V1_MODE_SUCCESSFUL 0
#define ZWP_FULLSCREEN_SHELL_MODE_FEEDBACK_V1_MODE_FAILED 1
#define ZWP_FULLSCREEN_SHELL_MODE_FEEDBACK_V1_PRESENT_CANCELLED 2

/**
 * @ingroup iface_zwp_fullscreen_shell_mode_feedback_v1
 */
#define ZWP_FULLSCREEN_SHELL_MODE_FEEDBACK_V1_MODE_SUCCESSFUL_SINCE_VERSION 1
/**
 * @ingroup iface_zwp_fullscreen_shell_mode_feedback_v1
 */
#define ZWP_FULLSCREEN_SHELL_MODE_FEEDBACK_V1_MODE_FAILED_SINCE_VERSION 1
/**
 * @ingroup iface_zwp_fullscreen_shell_mode_feedback_v1
 */
#define ZWP_FULLSCREEN_SHELL_MODE_FEEDBACK_V1_PRESENT_CANCELLED_SINCE_VERSION 1


/**
 * @ingroup iface_zwp_fullscreen_shell_mode_feedback_v1
 * Sends an mode_successful event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
zwp_fullscreen_shell_mode_feedback_v1_send_mode_successful(struct wl_resource *resource_)
{
	wl_resource_post_event(resource_, ZWP_FULLSCREEN_SHELL_MODE_FEEDBACK_V1_MODE_SUCCESSFUL);
}

/**
 * @ingroup iface_zwp_fullscreen_shell_mode_feedback_v1
 * Sends an mode_failed event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
zwp_fullscreen_shell_mode_feedback_v1_send_mode_failed(struct wl_resource *resource_)
{
	wl_resource_post_event(resource_, ZWP_FULLSCREEN_SHELL_MODE_FEEDBACK_V1_MODE_FAILED);
}

/**
 * @ingroup iface_zwp_fullscreen_shell_mode_feedback_v1
 * Sends an present_cancelled event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
zwp_fullscreen_shell_mode_feedback_v1_send_present_cancelled(struct wl_resource *resource_)
{
	wl_resource_post_event(resource_, ZWP_FULLSCREEN_SHELL_MODE_FEEDBACK_V1_PRESENT_CANCELLED);
}

#ifdef  __cplusplus
}
#endif

#endif
