#include "xdg_shell.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <wayland-server-core.h>

// Logging stub
#define LOG_STUB() fprintf(stderr, "[STUB] %s called\n", __func__)

// xdg_wm_base
void *xdg_wm_base_create(void *display) {
  LOG_STUB();
  return NULL;
}

void xdg_wm_base_destroy(void *wm_base) {
  LOG_STUB();
  (void)wm_base;
}

void xdg_wm_base_send_configure_to_all_toplevels(void *wm_base, int32_t width,
                                                 int32_t height) {
  // LOG_STUB(); // spammy
  (void)wm_base;
  (void)width;
  (void)height;
}

void xdg_wm_base_set_output_size(void *wm_base, int32_t width, int32_t height) {
  LOG_STUB();
  (void)wm_base;
  (void)width;
  (void)height;
}

// xdg_surface
struct xdg_toplevel_impl *
xdg_surface_get_toplevel_from_wl_surface(struct wl_surface_impl *wl_surface) {
  // LOG_STUB(); // spammy
  (void)wl_surface;
  return NULL;
}

// Protocol send stubs (formerly generated by wayland-scanner)
void xdg_surface_send_configure(struct wl_resource *resource, uint32_t serial) {
  // No-op
  (void)resource;
  (void)serial;
}

void xdg_toplevel_send_configure(struct wl_resource *resource, int32_t width,
                                 int32_t height, struct wl_array *states) {
  // No-op
  (void)resource;
  (void)width;
  (void)height;
  (void)states;
}

void xdg_toplevel_send_close(struct wl_resource *resource) {
  // No-op
  (void)resource;
}

void xdg_toplevel_send_configure_bounds(struct wl_resource *resource,
                                        int32_t width, int32_t height) {
  // No-op
  (void)resource;
  (void)width;
  (void)height;
}
