INCLUDES = -I../../shared -I../../.. -I/usr/local/include
SOURCES = core/RenderingBackend.m core/metal_dmabuf.m core/metal_waypipe.m rendering/renderer_macos.m rendering/renderer_ios.m rendering/renderer_android.c
HEADERS = core/RenderingBackend.h core/metal_dmabuf.h core/metal_waypipe.h rendering/renderer_macos.h rendering/renderer_ios.h rendering/renderer_android.h

all:
	@echo "This project is built using Nix. Please run 'nix build' or 'nix develop'."
