#pragma once

#include <wayland-server.h>
#include <wayland-util.h>

// Linux DMA-BUF protocol headers
// These would normally be generated by wayland-scanner

#ifndef ZWP_LINUX_DMABUF_V1_INTERFACE
#define ZWP_LINUX_DMABUF_V1_INTERFACE "zwp_linux_dmabuf_v1"
#endif

#ifndef ZWP_LINUX_BUFFER_PARAMS_V1_INTERFACE
#define ZWP_LINUX_BUFFER_PARAMS_V1_INTERFACE "zwp_linux_buffer_params_v1"
#endif

// Forward declarations
struct wl_linux_dmabuf_manager_impl;
struct wl_linux_buffer_params_impl;

// Linux DMA-BUF manager interface
struct zwp_linux_dmabuf_v1_interface {
    void (*destroy)(struct wl_client *client, struct wl_resource *resource);
    void (*create_params)(struct wl_client *client, struct wl_resource *resource,
                         uint32_t params_id);
    void (*get_default_feedback)(struct wl_client *client, struct wl_resource *resource,
                                uint32_t id);
    void (*get_surface_feedback)(struct wl_client *client, struct wl_resource *resource,
                                uint32_t id, struct wl_resource *surface);
};

// Linux buffer params interface
struct zwp_linux_buffer_params_v1_interface {
    void (*destroy)(struct wl_client *client, struct wl_resource *resource);
    void (*add)(struct wl_client *client, struct wl_resource *resource,
               int32_t fd, uint32_t plane_idx, uint32_t offset, uint32_t stride,
               uint32_t modifier_hi, uint32_t modifier_lo);
    void (*create)(struct wl_client *client, struct wl_resource *resource,
                  int32_t width, int32_t height, uint32_t format, uint32_t flags);
    void (*create_immed)(struct wl_client *client, struct wl_resource *resource,
                        uint32_t buffer_id, int32_t width, int32_t height,
                        uint32_t format, uint32_t flags);
};

// Extern declarations for interfaces
extern const struct wl_interface zwp_linux_dmabuf_v1_interface;
extern const struct wl_interface zwp_linux_buffer_params_v1_interface;

// Event opcodes
#define ZWP_LINUX_DMABUF_V1_FORMAT 0
#define ZWP_LINUX_DMABUF_V1_MODIFIER 1
#define ZWP_LINUX_BUFFER_PARAMS_V1_CREATED 0
#define ZWP_LINUX_BUFFER_PARAMS_V1_FAILED 1

// Error codes
#define ZWP_LINUX_BUFFER_PARAMS_V1_ERROR_ALREADY_USED 0
#define ZWP_LINUX_BUFFER_PARAMS_V1_ERROR_PLANE_IDX 1
#define ZWP_LINUX_BUFFER_PARAMS_V1_ERROR_PLANE_SET 2
#define ZWP_LINUX_BUFFER_PARAMS_V1_ERROR_INCOMPLETE 3
#define ZWP_LINUX_BUFFER_PARAMS_V1_ERROR_INVALID_FORMAT 4
#define ZWP_LINUX_BUFFER_PARAMS_V1_ERROR_INVALID_DIMENSIONS 5
#define ZWP_LINUX_BUFFER_PARAMS_V1_ERROR_OUT_OF_BOUNDS 6
#define ZWP_LINUX_BUFFER_PARAMS_V1_ERROR_INVALID_WL_BUFFER 7

// Function declarations
struct wl_linux_dmabuf_manager_impl *wl_linux_dmabuf_create(struct wl_display *display);
void wl_linux_dmabuf_destroy(struct wl_linux_dmabuf_manager_impl *dmabuf);

