#pragma once

#include <wayland-server.h>
#include <wayland-util.h>

// Viewporter protocol headers (generated from wayland-protocols)
// These would normally be generated by wayland-scanner, but we define them manually
// for now until we have the protocol XML files

#ifndef WP_VIEWPORTER_INTERFACE
#define WP_VIEWPORTER_INTERFACE "wp_viewporter"
#endif

#ifndef WP_VIEWPORT_INTERFACE
#define WP_VIEWPORT_INTERFACE "wp_viewport"
#endif

// Viewporter error codes
enum wp_viewporter_error {
    WP_VIEWPORTER_ERROR_VIEWPORT_EXISTS = 0,
};

enum wp_viewport_error {
    WP_VIEWPORT_ERROR_BAD_VALUE = 0,
};

// Forward declarations
struct wl_viewporter_impl;
struct wl_viewport_impl;

// Viewporter interface (minimal definition - full would come from wayland-scanner)
struct wp_viewporter_interface {
    void (*destroy)(struct wl_client *client, struct wl_resource *resource);
    void (*get_viewport)(struct wl_client *client, struct wl_resource *resource,
                         uint32_t id, struct wl_resource *surface);
};

struct wp_viewport_interface {
    void (*destroy)(struct wl_client *client, struct wl_resource *resource);
    void (*set_source)(struct wl_client *client, struct wl_resource *resource,
                       wl_fixed_t x, wl_fixed_t y, wl_fixed_t width, wl_fixed_t height);
    void (*set_destination)(struct wl_client *client, struct wl_resource *resource,
                            wl_fixed_t width, wl_fixed_t height);
};

// Extern declarations for interfaces (would be in generated header)
extern const struct wl_interface wp_viewporter_interface;
extern const struct wl_interface wp_viewport_interface;

// Function declarations
struct wl_viewporter_impl *wl_viewporter_create(struct wl_display *display);
void wl_viewporter_destroy(struct wl_viewporter_impl *viewporter);

