#pragma once

#include <wayland-server.h>
#include <wayland-util.h>

// Screencopy protocol headers
// These would normally be generated by wayland-scanner

#ifndef ZWP_SCREENCOPY_MANAGER_V1_INTERFACE
#define ZWP_SCREENCOPY_MANAGER_V1_INTERFACE "zwp_screencopy_manager_v1"
#endif

#ifndef ZWP_SCREENCOPY_FRAME_V1_INTERFACE
#define ZWP_SCREENCOPY_FRAME_V1_INTERFACE "zwp_screencopy_frame_v1"
#endif

// Forward declarations
struct wl_screencopy_manager_impl;
struct wl_screencopy_frame_impl;

// Screencopy manager interface
struct zwp_screencopy_manager_v1_interface {
    void (*destroy)(struct wl_client *client, struct wl_resource *resource);
    void (*capture_output)(struct wl_client *client, struct wl_resource *resource,
                          uint32_t overlay_cursor, struct wl_resource *output);
    void (*capture_output_region)(struct wl_client *client, struct wl_resource *resource,
                                  uint32_t overlay_cursor, struct wl_resource *output,
                                  int32_t x, int32_t y, int32_t width, int32_t height);
};

// Screencopy frame interface
struct zwp_screencopy_frame_v1_interface {
    void (*destroy)(struct wl_client *client, struct wl_resource *resource);
    void (*copy)(struct wl_client *client, struct wl_resource *resource,
                struct wl_resource *buffer);
    void (*copy_with_damage)(struct wl_client *client, struct wl_resource *resource,
                            struct wl_resource *buffer);
};

// Extern declarations for interfaces
extern const struct wl_interface zwp_screencopy_manager_v1_interface;
extern const struct wl_interface zwp_screencopy_frame_v1_interface;

// Event sending - use wl_resource_post_event directly with opcodes
// defined in wayland_screencopy.c

// Function declarations
struct wl_screencopy_manager_impl *wl_screencopy_manager_create(struct wl_display *display);
void wl_screencopy_manager_destroy(struct wl_screencopy_manager_impl *screencopy);

